// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuPQrmTzYBgzYvT7ew9CVbsou2kYmvn-4',
    appId: '1:1065683134046:web:43a5fcc3813358e0e4b6cf',
    messagingSenderId: '1065683134046',
    projectId: 'cinema-tikets',
    authDomain: 'cinema-tikets.firebaseapp.com',
    storageBucket: 'cinema-tikets.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgOL0u25xIC9k1eaMp6h_eR5Z9iPbLnU4',
    appId: '1:1065683134046:android:84381dc1361348c2e4b6cf',
    messagingSenderId: '1065683134046',
    projectId: 'cinema-tikets',
    storageBucket: 'cinema-tikets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC294YXSoEagTcocWoqlxT58WIlN6FCVBc',
    appId: '1:1065683134046:ios:0f63dd36468c10e9e4b6cf',
    messagingSenderId: '1065683134046',
    projectId: 'cinema-tikets',
    storageBucket: 'cinema-tikets.appspot.com',
    iosClientId: '1065683134046-3ja43mmj6a8mkbr9dmvh1oek9bus7cju.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemaTikets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC294YXSoEagTcocWoqlxT58WIlN6FCVBc',
    appId: '1:1065683134046:ios:0f63dd36468c10e9e4b6cf',
    messagingSenderId: '1065683134046',
    projectId: 'cinema-tikets',
    storageBucket: 'cinema-tikets.appspot.com',
    iosClientId: '1065683134046-3ja43mmj6a8mkbr9dmvh1oek9bus7cju.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemaTikets',
  );
}
